import localFont from "next/font/local";
import "./globals.css";

const apkProtocol = localFont({
  src: "../../public/fonts/Apk-Protocol-Regular-Trial.otf",
  variable: "--font-apk-protocol",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${apkProtocol.variable} antialiased`}>{children}</body>
    </html>
  );
}
